### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by Erlite** [ScottKaye/CoreRCON#6]
`Unhandled Exception: System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at CoreRCON.RCON.TCPPacketReceived(Object sender, SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncContext.SendReceiveOperation.InvokeCallback()
   at System.Net.Sockets.SocketAsyncContext.AsyncOperation.<>c.<QueueCompletionCallback>b__11_0(Object o)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
`

After sending RCON commands, my program crashes (after a small while) even with a couple of try catch statements. I have no idea why though.

**Comment by ScottKaye** [comment]
Unfortunately this repo is basically dead, I'm sorry but I have no idea what the issue could be anymore :(

**Comment by Erlite** [comment]
Ah, no problem. After testing I think I can safely blame .NET Core since it doesn't throw on my Windows PC, it works perfectly. On my Debian server however, it throws and uncatchable exception.
